#!/usr/bin/env bash

## \brief {FILENAME}

if [ $# -eq 0 ]; then
  doc usage "$0"
fi

main() {
  case $1 in
    ## \option -h, --help
    ## Print this help and exit.
    -h|--help) doc "$0"; exit 0 ;;
  esac
}

## \usage {FILENAME}
main "$@"
