#!/usr/bin/env bash

## \brief {FILENAME}

shellm-source shellm/shellman/lib/shellman.sh

[ $# -eq 0 ] && shellman_usage

main() {
  case $1 in
    ## \option -h, --help
    ## Print this help and exit.
    -h|--help) shellman "$0"; exit 0 ;;
  esac
}

## \usage {FILENAME}
main "$@"
